apiVersion: v1
kind: Service
metadata:
  name: nats-export-service
spec:
  selector:
    app: nats-export-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP